Repository googleapis/python-container, pull requests merged in 2020-06, with the labels that each got.

#24 feat: release as production/stable
  .repo-metadata.json
  README.rst
  setup.py
Labels: cla: yes

#27 fix: fix `release_status` in `setup.py`
  setup.py
Labels: automerge, cla: yes

#30 chore: add multiprocessing note
  .flake8
  .gitignore
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.7/continuous.cfg
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.7/presubmit.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.8/continuous.cfg
  .kokoro/samples/python3.8/periodic.cfg
  .kokoro/samples/python3.8/presubmit.cfg
  .kokoro/test-samples.sh
  MANIFEST.in
  docs/conf.py
  docs/index.rst
  docs/multiprocessing.rst
  google/cloud/container.py
  google/cloud/container_v1/__init__.py
  google/cloud/container_v1/gapic/cluster_manager_client.py
  google/cloud/container_v1/gapic/cluster_manager_client_config.py
  google/cloud/container_v1/gapic/enums.py
  google/cloud/container_v1/gapic/transports/cluster_manager_grpc_transport.py
  google/cloud/container_v1/proto/cluster_service.proto
  google/cloud/container_v1/proto/cluster_service_pb2.py
  google/cloud/container_v1/types.py
  google/cloud/container_v1beta1/__init__.py
  google/cloud/container_v1beta1/gapic/cluster_manager_client.py
  google/cloud/container_v1beta1/gapic/enums.py
  google/cloud/container_v1beta1/gapic/transports/cluster_manager_grpc_transport.py
  google/cloud/container_v1beta1/proto/cluster_service.proto
  google/cloud/container_v1beta1/proto/cluster_service_pb2.py
  google/cloud/container_v1beta1/types.py
  noxfile.py
  scripts/decrypt-secrets.sh
  scripts/readme-gen/readme_gen.py
  scripts/readme-gen/templates/README.tmpl.rst
  scripts/readme-gen/templates/auth.tmpl.rst
  scripts/readme-gen/templates/auth_api_key.tmpl.rst
  scripts/readme-gen/templates/install_deps.tmpl.rst
  scripts/readme-gen/templates/install_portaudio.tmpl.rst
  synth.metadata
  synth.py
  testing/.gitignore
  tests/unit/gapic/v1/test_cluster_manager_client_v1.py
Labels: cla: yes, context: full

#32 chore: update Py2 support msg to reflect passage of time
  docs/_templates/layout.html
  synth.metadata
Labels: cla: yes, context: full
