Repository googleapis/python-container, pull requests merged in 2020-12, with the labels that each got.

#53 docs(python): update intersphinx for grpc and auth
  docs/conf.py
  synth.metadata
Labels: api: container, automerge, cla: yes, context: full

#59 fix: Update CODEOWNERS
  .github/CODEOWNERS
Labels: api: container, automerge, cla: yes

#57 chore: add pre-commit hook
  .coveragerc
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  docs/conf.py
  noxfile.py
  synth.metadata
Labels: api: container, cla: yes, context: full

#62 chore(deps): update precommit hook pre-commit/pre-commit-hooks to v3.4.0
  .pre-commit-config.yaml
  synth.metadata
Labels: api: container, cla: yes, context: full

#60 fix: remove client recv msg limit and add enums to `types/__init__.py`
  google/cloud/container_v1/services/cluster_manager/transports/__init__.py
  google/cloud/container_v1/services/cluster_manager/transports/grpc.py
  google/cloud/container_v1/services/cluster_manager/transports/grpc_asyncio.py
  google/cloud/container_v1/types/__init__.py
  google/cloud/container_v1beta1/services/cluster_manager/transports/__init__.py
  google/cloud/container_v1beta1/services/cluster_manager/transports/grpc.py
  google/cloud/container_v1beta1/services/cluster_manager/transports/grpc_asyncio.py
  google/cloud/container_v1beta1/types/__init__.py
  synth.metadata
  tests/unit/gapic/container_v1/test_cluster_manager.py
  tests/unit/gapic/container_v1beta1/test_cluster_manager.py
Labels: api: container, cla: yes, context: full

#64 chore: exclude `.nox` from linting; document supported python versions
  .flake8
  CONTRIBUTING.rst
  synth.metadata
Labels: api: container, cla: yes, context: full
