Repository googleapis/python-container, pull requests merged in 2021-04, with the labels that each got.

#81 Test: update constraints files and use precommit hook
  .pre-commit-config.yaml
  noxfile.py
  synth.metadata
  testing/constraints-3.6.txt
Labels: api: container, cla: yes, context: full

#83 build(python): update docfx job to use new plugin
  noxfile.py
  synth.metadata
Labels: api: container, cla: yes, context: full

#85 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: container, automerge, cla: yes, context: full

#86 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: container, cla: yes, context: full, samples

#87 chore: Re-generated to pick up changes from synthtool
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: container, cla: yes, context: full

#88 chore: prevent normalization of semver versioning
  setup.py
Labels: api: container, automerge, cla: yes

#89 chore(revert): revert preventing normalization
  setup.py
Labels: api: container, cla: yes
