Repository googleapis/python-container, pull requests merged in 2021-05, with the labels that each got.

#92 [CHANGE ME] Re-generated to pick up changes from self.
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  noxfile.py
  synth.metadata
Labels: api: container, cla: yes, context: none

#93 chore: add library type to .repo-metadata.json
  .repo-metadata.json
Labels: api: container, automerge, cla: yes

#95 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
  synth.py
Labels: api: container, cla: yes

#97 fix(deps): add packaging requirement
  setup.py
  testing/constraints-3.6.txt
Labels: api: container, automerge, cla: yes

#100 chore: add cicd (devplat) team to codeowners
  .repo-metadata.json
Labels: api: container, cla: yes
